### ISSUE TITLE
Lock and Remote Ignition

### ISSUE THREAD

**Issue by TechJeeper** [G-Two/subarulink#32]
It looks like Subaru is blocking Lock and Ignition calls

**Comment by RaghavRao** [comment]
Works fine for me, just tested

**Comment by G-Two** [comment]
@TechJeeper I haven't had any issues sending remote commands for the past week. Once in awhile the service is unavailable globally (including via the official app). Maybe you ran into one of those periods? I assume it was working for you in the past. Do you have any logs you can share to help pin point the issue?

**Comment by TechJeeper** [comment]
The error I get at the ignition call is Failed to call service binary_sensor/turn_on. Service not found.

I can start the car from the my
![Screenshot_20210120-075127](https://user-images.githubusercontent.com/5033913/105177352-8e3fd480-5af4-11eb-90cf-53499ad9c5e5.png)
Subaru app.

**Comment by stboch** [comment]
There is a remote start service the binary sensor is just status not a stop start on/off switch.

**Comment by G-Two** [comment]
@TechJeeper here's a UI yaml example for a button that will call the remote start service.
```
type: button
icon: 'mdi:power'
icon_height: 32px
name: Remote Start
show_icon: true
show_name: true
tap_action:
  action: call-service
  confirmation:
    text: Remote Start?
  service: subaru.remote_start
  service_data:
    vin: <VIN>
```
All the other [services](https://github.com/G-Two/homeassistant-subaru/blob/main/services.md) are similar.
