### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by chvvkumar** [G-Two/subarulink#36]
Just installed it and it's working great with my 2020 Outback!

A few of the sensors are missing compared to your dashboard but I am chalking it up to to what information StarLink collects.

https://github.com/chvvkumar/subaru_outback

**Comment by G-Two** [comment]
@chvvkumar good to hear, thanks for sharing your dash! Your 2020 Outback should be able to support everything I have on mine except for the EV charging features. Things like lights/horn/remote_start are only exposed via [services](https://github.com/G-Two/homeassistant-subaru/blob/main/services.md). Here's a snippet of how I made buttons to interact with the features. You'll just need to add your VIN, and omit the EV specific things.

```
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - entity: ''
        hold_action:
          action: more-info
        icon: 'mdi:refresh'
        icon_height: 32px
        name: Refresh
        show_icon: true
        show_name: true
        show_state: false
        tap_action:
          action: call-service
          service: subaru.fetch
          service_data:
            vin: <YOUR_VIN_HERE>
        type: button
      - entity: ''
        hold_action:
          action: more-info
        icon: 'mdi:car-connected'
        icon_height: 32px
        name: Poll Vehicle
        show_icon: true
        show_name: true
        show_state: false
        tap_action:
          action: call-service
          confirmation:
            text: Poll Vehicle?
          service: subaru.update
          service_data:
            vin: <YOUR_VIN_HERE>
        type: button
    title: Update Data
  - type: vertical-stack
    title: Remote Commands
    cards:
      - cards:
          - icon: 'mdi:lock'
            icon_height: 32px
            name: Lock
            show_icon: true
            show_name: true
            tap_action:
              action: call-service
              confirmation:
                text: Lock Doors?
              service: subaru.lock
              service_data:
                vin: <YOUR_VIN_HERE>
            type: button
          - entity: ''
            icon: 'mdi:lock-open-variant'
            icon_height: 32px
            name: Unlock
            show_icon: true
            show_name: true
            show_state: false
            tap_action:
              action: call-service
              confirmation:
                text: Unlock Doors?
              service: subaru.unlock
              service_data:
                vin: <YOUR_VIN_HERE>
            type: button
        type: horizontal-stack
      - cards:
          - entity: ''
            hold_action:
              action: more-info
            icon: 'mdi:lightbulb-on'
            icon_height: 32px
            name: Flash Lights
            show_icon: true
            show_name: true
            show_state: false
            tap_action:
              action: call-service
              confirmation:
                text: Flash lights?
              service: subaru.lights
              service_data:
                vin: <YOUR_VIN_HERE>
            type: button
          - entity: ''
            hold_action:
              action: more-info
            icon_height: 32px
            icon: 'mdi:lightbulb-off'
            name: Stop Lights
            show_icon: true
            show_name: true
            show_state: false
            tap_action:
              action: call-service
              confirmation:
                text: Stop lights?
              service: subaru.lights_stop
              service_data:
                vin: <YOUR_VIN_HERE>
            type: button
        type: horizontal-stack
      - cards:
          - entity: ''
            hold_action:
              action: more-info
            icon: 'mdi:volume-high'
            icon_height: 32px
            name: Sound Horn
            show_icon: true
            show_name: true
            show_state: false
            tap_action:
              action: call-service
              confirmation:
                text: Sound horn?
              service: subaru.horn
              service_data:
                vin: <YOUR_VIN_HERE>
            type: button
          - entity: ''
            hold_action:
              action: more-info
            icon_height: 32px
            icon: 'mdi:volume-off'
            name: Stop Horn
            show_icon: true
            show_name: true
            show_state: false
            tap_action:
              action: call-service
              confirmation:
                text: Stop horn?
              service: subaru.horn_stop
              service_data:
                vin: <YOUR_VIN_HERE>
            type: button
        type: horizontal-stack
      - cards:
          - type: button
            hold_action:
              action: more-info
            icon: 'mdi:power'
            icon_height: 32px
            name: Remote Start
            show_icon: true
            show_name: true
            tap_action:
              action: call-service
              confirmation:
                text: Remote Start?
              service: subaru.remote_start
              service_data:
                vin: <YOUR_VIN_HERE>
          - entity: ''
            hold_action:
              action: more-info
            icon: 'mdi:stop'
            icon_height: 32px
            name: Remote Stop
            show_icon: true
            show_name: true
            tap_action:
              action: call-service
              confirmation:
                text: Remote Stop?
              service: subaru.remote_stop
              service_data:
                vin: <YOUR_VIN_HERE>
            type: button
        type: horizontal-stack
  - cards:
      - cards:
          - entity: ''
            hold_action:
              action: more-info
            icon: 'mdi:battery-charging'
            icon_height: 32px
            name: Begin Charging
            show_icon: true
            show_name: true
            show_state: false
            tap_action:
              action: call-service
              confirmation:
                text: Begin Charging?
              service: subaru.charge_start
              service_data:
                vin: <YOUR_VIN_HERE>
            type: button
          - entity: sensor.crosstrek_ev_battery_level
            name: EV Battery Level
            type: entity
        type: horizontal-stack
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entity
                entity: binary_sensor.crosstrek_ev_charge_port
                name: Plugged In
              - type: entity
                entity: sensor.crosstrek_ev_time_to_full_charge
                name: Time to Full Charge
    type: vertical-stack
    title: EV Functions

```
